# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-10-10 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ground',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=500)),
                ('is_closed', models.IntegerField(default=0)),
                ('is_active', models.IntegerField(default=0)),
                ('week_day_rate', models.CharField(default='0.0', max_length=50)),
                ('week_end_rate', models.CharField(default='0.0', max_length=50)),
                ('is_disable', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'ground',
            },
        ),
    ]
