# Generated by Django 3.1 on 2020-10-31 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20201010_0733'),
    ]

    operations = [
        migrations.AddField(
            model_name='ground',
            name='contact',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ground',
            name='email',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ground',
            name='state',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
