# Generated by Django 3.1 on 2020-11-01 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20201031_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='ground',
            name='slot_duration',
            field=models.IntegerField(default=60),
        ),
    ]
