# Generated by Django 3.1 on 2020-11-15 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_ground_slot_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
