# Generated by Django 3.1 on 2020-11-22 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_bookings_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ground',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ground',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ground',
            name='is_disable',
            field=models.BooleanField(default=False),
        ),
    ]
